AWSTemplateFormatVersion: '2010-09-09'
Description: 'Serverless API Gateway HTTP API with Lambda function (Python) - Cost Optimized'

Parameters:
  LambdaFunctionName:
    Type: String
    Default: serverless-api-handler
    Description: Name for the Lambda function
  
  ApiName:
    Type: String
    Default: serverless-api
    Description: Name for the API Gateway HTTP API

Resources:
  # Lambda Execution Role
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${LambdaFunctionName}-execution-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: CloudWatchLogsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${LambdaFunctionName}:*'

  # Lambda Function
  ApiHandlerFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref LambdaFunctionName
      Runtime: python3.12
      Handler: handler.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import json
          
          def lambda_handler(event, context):
              http_method = event.get("requestContext", {}).get("http", {}).get("method", "GET")
              path = event.get("requestContext", {}).get("http", {}).get("path", "/")
              
              if path == "/hello":
                  response_data = {
                      "message": "Hello from AWS Lambda!",
                      "method": http_method,
                      "path": path,
                  }
              else:
                  response_data = {
                      "message": "Welcome to AWS Serverless API",
                      "method": http_method,
                      "path": path,
                  }
              
              return {
                  "statusCode": 200,
                  "headers": {
                      "Content-Type": "application/json",
                      "Access-Control-Allow-Origin": "*",
                  },
                  "body": json.dumps(response_data),
              }
      Timeout: 30
      MemorySize: 128  # Minimum memory for cost optimization
      Environment:
        Variables:
          ENV: production

  # CloudWatch Log Group with retention
  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${LambdaFunctionName}'
      RetentionInDays: 7  # Cost optimization: keep logs for 1 week only

  # API Gateway HTTP API (cheaper than REST API)
  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Ref ApiName
      ProtocolType: HTTP
      Description: Serverless API Gateway HTTP API - Cost Optimized
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowMethods:
          - GET
          - POST
          - OPTIONS
        AllowHeaders:
          - '*'
        MaxAge: 86400

  # API Gateway Integration
  ApiIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ApiHandlerFunction.Arn}/invocations'
      PayloadFormatVersion: '2.0'

  # API Gateway Route - Root
  ApiRouteRoot:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'GET /'
      Target: !Sub 'integrations/${ApiIntegration}'

  # API Gateway Route - Hello
  ApiRouteHello:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'GET /hello'
      Target: !Sub 'integrations/${ApiIntegration}'

  ApiRouteHelloPost:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'POST /hello'
      Target: !Sub 'integrations/${ApiIntegration}'

  # API Gateway Stage
  ApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HttpApi
      StageName: '$default'
      AutoDeploy: true
      DefaultRouteSettings:
        ThrottlingBurstLimit: 100
        ThrottlingRateLimit: 50

  # Lambda Permission for API Gateway
  LambdaApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ApiHandlerFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/*/*'

Outputs:
  ApiUrl:
    Description: HTTP API Gateway URL
    Value: !Sub 'https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com'
    Export:
      Name: !Sub '${AWS::StackName}-ApiUrl'
  
  LambdaFunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt ApiHandlerFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-LambdaArn'
